@startuml
participant "Client" as c
participant "Server" as s
... 0.000 ...
c -> s: [SYN] + Client-Hello
... 0.010 ...
c <- s: [SYN,ACK]
... 0.017 ...
c <- s: Server Hello, Change Cipher Spec, ...
... 0.019 ...
c -> s: [ACK]
... 0.029 ...
c -> s: Change Cipher Spec, Finished
c -> s: PING
... 0.039 ...
c <- s: New Session Ticket
c <- s: New Session Ticket
c <- s: PONG
c <- s: Alert: Close Notify
... 0.049 ...
c -> s: Alert: Close Notify
c -> s: [FIN,ACK]
... 0.059 ...
c <- s: [FIN,ACK]
@enduml
