@startuml
participant "Client" as c
participant "Server" as s
... 0.000 ...
c -> s: [SYN]
... 0.010 ...
c <- s: [SYN, ACK]
... 0.020 ...
c -> s: [ACK]
... 0.020 ...
c -> s: TLSv1 Client Hello
... 0.030 ...
c <- s: [ACK]
... 0.037 ...
c <- s: Server Hello, Certificate, Server Key Exchange, Server Hello Done
... 0.048 ...
c -> s: Client Key Exchange, Change Cipher Spec, Finished
... 0.058 ...
c <- s: New Session Ticket, Change Cipher Spec, Finished
... 0.069 ...
c -> s: Application Data, Application Data
... 0.079 ...
c <- s: Application Data, Application Data
c <- s: Alert: Close Notify
... 0.089 ...
c -> s: Alert: Close Notify
c -> s: [FIN, ACK]
... 0.099 ...
c <- s: [FIN, ACK]
@enduml

