@startuml
participant "Client" as c
participant "Server" as s
... 0.000 ...
c -> s: [SYN] + Client-Hello, Change Cipher Spec, PING
... 0.010 ...
c <- s: [SYN, ACK]
... 0.011 ...
c <- s: Server Hello, Change Cipher Spec, Finished
... 0.019 ...
c -> s: [ACK]
... 0.022 ...
c -> s: End of Early Data, Finished
... 0.032 ...
c <- s: New Session Ticket
c <- s: PONG
c <- s: Alert: Close Notify
... 0.042 ...
c -> s: Alert: Close Notify
c -> s: [FIN]
... 0.052 ...
c <- s: [FIN]
@enduml
