@startuml
participant "Client" as c
participant "Server" as s
... 0.000 ...
c -> s: [SYN]
... 0.010 ...
c <- s: [SYN, ACK]
... 0.020 ...
c -> s: [ACK]
c -> s: Client Hello
... 0.030 ...
c <- s: [ACK]
... 0.038 ...
c <- s: Server Hello, Change Cipher Spec, ...
... 0.049 ...
c -> s: Change Cipher Spec, Finished
c -> s: PING
... 0.059 ...
c <- s: New Session Ticket
c <- s: New Session Ticket
c <- s: PONG
c <- s: Alert: Close Notify
... 0.069 ...
c -> s: Alert: Close Notify
c -> s: [FIN, ACK]
... 0.079 ...
c <- s: [FIN, ACK]
@enduml
