@startuml
participant "Client" as c
participant "Server" as s
... 0.000 ...
c -> s: [SYN]
... 0.010 ...
c <- s: [SYN, ACK]
... 0.020 ...
c -> s: [ACK]
c -> s: Client Hello, Change Cipher Spec, PING
... 0.031 ...
c <- s: Server Hello, Change Cipher Spec, Finished
... 0.042 ...
c -> s: End of Early Data, Finished
... 0.052 ...
c <- s: New Session Ticket
c <- s: PONG
c <- s: Alert: Close Notify
... 0.062 ...
c -> s: Alert: Close Notify
c -> s: [FIN, ACK]
... 0.072 ...
c <- s: [FIN, ACK]
@enduml
